export const types ={
    //Login functionality 
    CREATE_LOGIN : 'CREATE_LOGIN',
    CREATE_LOGIN_SUCCESS : 'CREATE_LOGIN_SUCCESS',
    CREATE_LOGIN_FAILURE :'CREATE_LOGIN_FAILURE',

//password functionality 
    CREATE_PASSWORD : 'CREATE_PASSWORD',
    CREATE_PASSWORD_SUCCESS : 'CREATE_PASSWORD_SUCCESS',
    CREATE_PASSWORD_FAILURE :'CREATE_PASSWORD_FAILURE',   
}